{% set name = "pymt_ku" %}
{% set data = load_setup_py_data() %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - numpy 1.11.*
    - cython
    - model_metadata
    - permamodel

  run:
    - python
    - setuptools
    - pymt
    - permamodel

test:
  requires:
    - bmi-tester
  imports:
    - pymt_ku
  commands:
    - bmi-test pymt_ku:BmiKuMethod --infile=$(mmd-stage BmiKuMethod .)

about:
  summary: PyMT plugin for ku.
  home: https://github.com/mcflugen/pymt_ku
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_ku
